# NUMPY TUTORIAL

### Lab 1 — Understanding NumPy Arrays

In [12]:
import numpy as np

In [13]:
array = np.array([1,2,3,4,5])
print(array)
print(type(array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


### 1.1 Python List vs NumPy Array

In [14]:

# Difference between Python list and Numpy array

py_list = [1,2,3,4,5]

print("This is a python List: ",py_list)
print("This is a Numpy array: ",array)

array = array*2
py_list = py_list*2

print("\nAfter multiplying both with 2\n")



print("This is a python List: ",py_list)
print("This is a Numpy array: ",array)


This is a python List:  [1, 2, 3, 4, 5]
This is a Numpy array:  [1 2 3 4 5]

After multiplying both with 2

This is a python List:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
This is a Numpy array:  [ 2  4  6  8 10]


### Lab 2 — Multidimensional Arrays

In [18]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

b = np.array(a)


print("Two dimentional list        : ")
print(a)
print("Two dimentional Numpy Array : ")
print(b)


c = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("Three dimentional Numpy Array : ")
print(c)

Two dimentional list        : 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Two dimentional Numpy Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Three dimentional Numpy Array : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Lab 3 — Array Attributes

In [34]:
two_dim = np.array([
    [1,2,3,4,5],[6,7,8,9,10]
])

print("Dimentions of Array: ",two_dim.ndim)
print("Shape of array: ",two_dim.shape)
print("Size of array: ",two_dim.size)
print("Datatype of array: ",two_dim.dtype)


Dimentions of Array:  2
Shape of array:  (2, 5)
Size of array:  10
Datatype of array:  int64


### Lab 4 — Indexing

In [ ]:
marks = np.array([78,89,81,81,73])

subj_marks = {
    "TOA": 81,
    "COAL": 81,
    "AI": 73,
    "IS": 78
}

for k,v in subj_marks.items():
    print(k,": ",v)

toa_marks = marks[2]
print("Theory of Automata marks: ",toa_marks)

TOA :  81
COAL :  81
AI :  73
IS :  78
{'TOA': 81, 'COAL': 81, 'AI': 73, 'IS': 78}
Theory of Automata marks:  81


#### 4.1 2D indexing

In [42]:
two_dim = np.array([
    [1,2,3],
    [4,5,6]
])


print(two_dim[1,2])

6


### Lab 5 — Slicing

This is one of the most important NumPy skills.

In [55]:
# array[start:stop:step]

numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odd = numbers[1::2]
print("Odd numbers: ",odd)

even = numbers[::2]
print("Even numbers: ",even)

print(numbers[::-1])

Odd numbers:  [1 3 5 7 9]
Even numbers:  [ 0  2  4  6  8 10]
[10  9  8  7  6  5  4  3  2  1  0]


#### 5.1 2D slicing

In [58]:
data = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])


two_rows = data[0:2]
print(two_rows)


"""
    [1,2,3],
    [5,6,7]
"""
# three columns of first two rows
print(data[0:2,0:3])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [5 6 7]]
