# NUMPY TUTORIAL

### Lab 1 — Understanding NumPy Arrays

In [12]:
import numpy as np

In [13]:
array = np.array([1,2,3,4,5])
print(array)
print(type(array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


### 1.1 Python List vs NumPy Array

In [14]:

# Difference between Python list and Numpy array

py_list = [1,2,3,4,5]

print("This is a python List: ",py_list)
print("This is a Numpy array: ",array)

array = array*2
py_list = py_list*2

print("\nAfter multiplying both with 2\n")



print("This is a python List: ",py_list)
print("This is a Numpy array: ",array)


This is a python List:  [1, 2, 3, 4, 5]
This is a Numpy array:  [1 2 3 4 5]

After multiplying both with 2

This is a python List:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
This is a Numpy array:  [ 2  4  6  8 10]


### Lab 2 — Multidimensional Arrays

In [18]:
a = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

b = np.array(a)


print("Two dimentional list        : ")
print(a)
print("Two dimentional Numpy Array : ")
print(b)


c = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("Three dimentional Numpy Array : ")
print(c)

Two dimentional list        : 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Two dimentional Numpy Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Three dimentional Numpy Array : 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Lab 3 — Array Attributes

In [34]:
two_dim = np.array([
    [1,2,3,4,5],[6,7,8,9,10]
])

print("Dimentions of Array: ",two_dim.ndim)
print("Shape of array: ",two_dim.shape)
print("Size of array: ",two_dim.size)
print("Datatype of array: ",two_dim.dtype)


Dimentions of Array:  2
Shape of array:  (2, 5)
Size of array:  10
Datatype of array:  int64


### Lab 4 — Indexing

In [ ]:
marks = np.array([78,89,81,81,73])

subj_marks = {
    "TOA": 81,
    "COAL": 81,
    "AI": 73,
    "IS": 78
}

for k,v in subj_marks.items():
    print(k,": ",v)

toa_marks = marks[2]
print("Theory of Automata marks: ",toa_marks)

TOA :  81
COAL :  81
AI :  73
IS :  78
{'TOA': 81, 'COAL': 81, 'AI': 73, 'IS': 78}
Theory of Automata marks:  81


#### 4.1 2D indexing

In [42]:
two_dim = np.array([
    [1,2,3],
    [4,5,6]
])


print(two_dim[1,2])

6


### Lab 5 — Slicing

This is one of the most important NumPy skills.

In [55]:
# array[start:stop:step]

numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odd = numbers[1::2]
print("Odd numbers: ",odd)

even = numbers[::2]
print("Even numbers: ",even)

print(numbers[::-1])

Odd numbers:  [1 3 5 7 9]
Even numbers:  [ 0  2  4  6  8 10]
[10  9  8  7  6  5  4  3  2  1  0]


#### 5.1 2D slicing

In [58]:
data = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])


two_rows = data[0:2]
print(two_rows)


"""
    [1,2,3],
    [5,6,7]
"""
# three columns of first two rows
print(data[0:2,0:3])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [5 6 7]]


### Lab 6 — Arithmetic Operations

In [76]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])



print(a+b)
print(a*b)
print(a-b)
print(a//b)
print(a/b)


sq = [4,9,16]
print(b*2)

print(np.sqrt(sq))

[11 22 33 44]
[ 10  40  90 160]
[ 9 18 27 36]
[10 10 10 10]
[10. 10. 10. 10.]
[2 4 6 8]
[2. 3. 4.]


### Lab 7 — Broadcasting

In [81]:
marks = np.array([60, 70, 80, 90])
print(marks)
marks = marks+5
print(marks)


print("\n\nTwo Dimentions\n\n")

marks = np.array([
    [60, 70, 80],
    [50, 65, 75]
])

print(marks)
marks = marks+5
print(marks)

[60 70 80 90]
[65 75 85 95]


Two Dimentions


[[60 70 80]
 [50 65 75]]
[[65 75 85]
 [55 70 80]]


### Lab 8 — Aggregate Functions

In [87]:
marks = np.array([65, 72, 81, 90, 55, 88])


average_marks = np.average(marks)
print("Sum of marks: ",np.sum(marks))
print("Average: ",average_marks)
print("Highest marks: ",np.max(marks))
print("Lowest marks: ",np.min(marks))
print("Standard deviation: ",np.std(marks))


# python's builtin sum() is slower than the NumpPy's sum
# NumPy's sum is written in optimized C language
print("Sum of marks: ",sum(marks))

Sum of marks:  451
Average:  75.16666666666667
Highest marks:  90
Lowest marks:  55
Standard deviation:  12.508885730640527
Sum of marks:  451


### Lab 9 — Aggregation Across Rows and Columns

This is where NumPy becomes much more useful for data science.

**` his axis concept is something you should master, because it appears constantly in NumPy, Pandas, and ML preprocessing. `** 


In [96]:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [90, 95, 88]
])



mean_of_marks = np.mean(marks)
print("Mean of entire marks: ",mean_of_marks)

# Average for each column
# print("Average of columns: ")
# for index , avg in enumerate (np.mean(marks, axis=0)):
#     print(f"Column number {index}: {avg}")

print("Average of rows: ")
for index , avg in enumerate (np.mean(marks, axis=1)):
    print(f"Column number {index}: {avg}")

print("Check the accuracy of mean")
print("Column number 0: ",np.mean([70, 80, 90]))
print("Column number 1: ",np.mean([60, 75, 85]))
print("Column number 2: ",np.mean([90, 95, 88]))

Mean of entire marks:  81.44444444444444
Average of rows: 
Column number 0: 80.0
Column number 1: 73.33333333333333
Column number 2: 91.0
Check the accuracy of mean
Column number 0:  80.0
Column number 1:  73.33333333333333
Column number 2:  91.0


### Lab 10 — Filtering

Filtering means:

"Give me only the values that satisfy a condition."

In [ ]:
marks = np.array([45, 67, 82, 91, 55, 38, 76])


pass_student = marks[marks >= 60]
fail_student = marks[marks < 60]

print("Passing marks: ",pass_student)
print("Failing marks: ",fail_student)


# gives the values where the condition is True.
# This is called Boolean indexing/masking.

check = marks > 60
print(check)




Passing marks:  [67 82 91 76]
Failing marks:  [45 55 38]
[False  True  True  True False False  True]
[67 82 91 76]


### Lab 11 — Multiple Conditions
Find marks greater than 60 AND less than 90.

In [111]:
resutl = marks[(marks > 60) & (marks < 90)]

print(resutl)
 

[67 82 76]


### Lab 12 — Random Numbers

NumPy contains a random-number module.

Modern NumPy recommends using a random generator such as:

In [168]:
rng = np.random.default_rng()

numbers = rng.integers(1,101,12)
print(type(numbers))



# Random 2D array

a = rng.integers(
    1,
    101,
    (3,3)
)

print(a)


a = np.ones((2,3),dtype=str)

print(a)




a = np.zeros((2,3),dtype=int)

print(a)

<class 'numpy.ndarray'>
[[24 46 10]
 [34 78 53]
 [70 67 87]]
[['1' '1' '1']
 ['1' '1' '1']]
[[0 0 0]
 [0 0 0]]


### Lab 13 — Mini AI/ML Dataset

Now combine everything.

In [209]:
rng = np.random.default_rng(42)

marks = rng.integers(40,101,(10,3))
print(marks)

"""
# Assume
# Column 0 → Python
# Column 1 → Mathematics
# Column 2 → Machine Learning

Task 1

Find the average mark of each subject.

"""


for index, avg in enumerate(np.average(marks,axis = 0)):

    if index == 0:
        print(f"Average marks taken in Python: {avg}")
    elif index == 1:
        print(f"Average marks taken in maths: {avg}")
    elif index == 2:
        print(f"Average marks taken in Machine Learning: {avg}")


   

[[45 87 79]
 [66 66 92]
 [45 82 52]
 [45 72 99]
 [84 86 83]
 [87 71 47]
 [91 67 70]
 [62 51 96]
 [87 79 64]
 [90 73 67]]
Average marks taken in Python: 70.2
Average marks taken in maths: 73.4
Average marks taken in Machine Learning: 74.9


In [210]:
# Task 2:
# Average marks of each Student
for index, avg in enumerate(np.average(marks,axis = 1)):
    print(f"Average marks of student {index+1}: {avg}")


Average marks of student 1: 70.33333333333333
Average marks of student 2: 74.66666666666667
Average marks of student 3: 59.666666666666664
Average marks of student 4: 72.0
Average marks of student 5: 84.33333333333333
Average marks of student 6: 68.33333333333333
Average marks of student 7: 76.0
Average marks of student 8: 69.66666666666667
Average marks of student 9: 76.66666666666667
Average marks of student 10: 76.66666666666667


#### Task 3
Find the highest mark in each subject.

In [211]:
highest_marks = np.max(marks)
print("Highest marks in out of 10 Students: ",highest_marks)

Highest marks in out of 10 Students:  99


#### Task 4

Find students whose average is above 70.

In [215]:
grade_a_students = np.mean(marks) > 70 

print(grade_a_students)
print(marks[grade_a_students])

True
[[[45 87 79]
  [66 66 92]
  [45 82 52]
  [45 72 99]
  [84 86 83]
  [87 71 47]
  [91 67 70]
  [62 51 96]
  [87 79 64]
  [90 73 67]]]
